import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/shortlandpg">ShortLandpg</Link>
        </li>
        <li>
          <Link to="/landpgvone">LandpgvOne</Link>
        </li>
        <li>
          <Link to="/founderslandpg">Founderslandpg</Link>
        </li>
        <li>
          <Link to="/lgvtwo">LgvTwo</Link>
        </li>
        <li>
          <Link to="/categ">Categ</Link>
        </li>
        <li>
          <Link to="/categlg">Categlg</Link>
        </li>
        <li>
          <Link to="/high">High</Link>
        </li>
        <li>
          <Link to="/onclicklg">OnClicklg</Link>
        </li>
        <li>
          <Link to="/codetailedloginuser">CoDetailedLoginUser</Link>
        </li>
        <li>
          <Link to="/job">Job</Link>
        </li>
        <li>
          <Link to="/forum">Forum</Link>
        </li>
        <li>
          <Link to="/picksectororlocat">PickSectororLocat</Link>
        </li>
        <li>
          <Link to="/companiespg">Companiespg</Link>
        </li>
        <li>
          <Link to="/onclick">OnClick</Link>
        </li>
        <li>
          <Link to="/portfol">Portfol</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
